version: '3.7'

volumes:
  letsencrypt:
    driver: local

networks:
  net:

services:
  proxy:
    container_name: proxy
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    networks:
      - net
  grav:
    container_name: grav
    image: bozzochet/docker-grav:herd
    expose: 80
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.grav-redirect-ssl.redirectscheme.scheme=https"
      - "traefik.http.routers.grav-nossl.middlewares=minio-redirect-ssl"
      - "traefik.http.routers.grav-nossl.rule=Host(`${DNS_NAME}`)"
      - "traefik.http.routers.grav-nossl.entrypoints=web"
      - "traefik.http.routers.grav.rule=Host(`${DNS_NAME}`)"
      - "traefik.http.routers.grav.entrypoints=websecure"
      - "traefik.http.routers.grav.tls=true"
      - "traefik.http.services.grav.loadbalancer.server.port=80"
